# Generated by Django 2.2.4 on 2021-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('birthDate', models.DateField()),
                ('passwd', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted'), ('inactive', 'inactive'), ('Suspended', 'Suspended')], default='active', max_length=25)),
                ('privilage', models.IntegerField(choices=[(9, 9), (8, 8), (7, 7), (1, 1), (0, 0)], default=9)),
                ('sex', models.CharField(choices=[('m', 'm'), ('f', 'f')], max_length=2)),
                ('mobile', models.CharField(max_length=15)),
                ('raters', models.IntegerField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
